services:
  local-database:
    image: "postgres:16.3"
    env_file:
      - postgres.env
    ports:
      - "5432:5432"
    volumes:
      - pg-volume:/var/lib/postgresql/data/
volumes:
  pg-volume: {}